name: Build
on: 
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout pixie-firmware
      uses: actions/checkout@v3
      with:
        repository: yuetloo/pixie-firmware
        path: pixie-firmware
        ref: v0.0.1
    - name: Verify assets
      run: ls -l ${{ github.workspace }}
