name: Build
on: 
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout pixie-firmware
      uses: actions/checkout@v3
      with:
        repository: yuetloo/pixie-firmware
        path: pixie-firmware
        ref: v0.0.1
    - name: Verify user
      run: echo $UID
    - name: Build pixie-firmware using Docker
      run: |
        cd pixie-firmware
        docker run --rm -v $PWD:/project -w /project -u $UID -e HOME=/tmp espressif/idf idf.py build
    - name: Verify assets
      run: ls -R ${{ github.workspace }}/pixie-firmware/build
  