name: Add documentation tag
on: 
  pull_request:
  workflow_dispatch:

jobs:
  check:
    name: Check modified files
    outputs:
        run_job: ${{ steps.check_files.outputs.run_job }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: check modified files
        id: check_files
        run: |
          echo "=============== list modified files ==============="
          git diff --name-only HEAD^ HEAD | tee files.txt

          echo "========== check paths of modified files =========="
          while IFS= read -r file
          do
            echo $file
            if [[ $file != docs/* ]]; then
              echo "This modified file is not under the 'docs' folder."
              echo "run_job=false" >> $GITHUB_OUTPUT
              break
            else
              echo "run_job=true" >> $GITHUB_OUTPUT
            fi
          done < files.txt

  tag_documentation:
    name: Add 'documentation' label
    permissions:
      pull-requests: write
    needs: check
    if: needs.check.outputs.run_job == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: add documentation tag
        run: gh pr edit "$NUMBER" --add-label "$LABELS"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.pull_request.number }}
          LABELS: documentation